### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Avonae**
*Thank you for contributing to subs ! So that your Pull Request can be handled effectively, please populate the following fields (delete sections that are not applicable)*

### Category
Documentation

### Overview
Add docker installation

### CODE REVIEW

**Comment by Avonae** [comment]
sure

**Comment by Avonae** [comment]
it works but i got this errors: 

```
Error: Cannot find module '@libsql/linux-x64-musl'
Require stack:
- /app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at /app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requireNative (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:22:10)
    at Object.<anonymous> (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:45:5)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js'
  ]
}
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
```

**Comment by Avonae** [comment]
I also found out that my changes doesn't save actually:
image
I've deleted couple services and here they are again after F%

**Comment by ajnart** [comment]
> it works but i got this errors:
> 
> ```
> Error: Cannot find module '@libsql/linux-x64-musl'
> Require stack:
> - /app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
>     at /app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:55:36
>     at Module._load (node:internal/modules/cjs/loader:1051:27)
>     at Module.require (node:internal/modules/cjs/loader:1311:19)
>     at mod.require (/app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
>     at require (node:internal/modules/helpers:179:18)
>     at requireNative (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:22:10)
>     at Object.<anonymous> (/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js:45:5)
>     at Module._compile (node:internal/modules/cjs/loader:1469:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/app/node_modules/.pnpm/libsql@0.4.6/node_modules/libsql/index.js'
>   ]
> }
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
>  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
> ```

Interesting, I think it means you don't have the correct binary to use the database, so it cannot write to it. I will look into it

**Comment by ajnart** [comment]
Closing this PR as no longer relevant. Feel free to do another one to include instructions about how you started the docker container

**Pull request closed without merging**
